title: NapongiZero's Blog
description: "Another Security Blog"
author:
  name: "NapongiZero"
  email: "S0rry@try.4g41n"
  url: "https://napongizero.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "NapongiZero"
year : "2021"
google_analytics: "G-MXJ9D7WCBZ"
